name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew update
        brew install cmake sqlite
        echo "CC=$(which clang)" >> $GITHUB_ENV
        echo "CXX=$(which clang++)" >> $GITHUB_ENV
        # Установка GoogleTest вручную
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        sudo cmake --install build
        cd ..
    - name: Configure and build
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
    - name: Verify binary
      run: |
        ./build/bin/tourism_bureau --help || true
        file ./build/bin/tourism_bureau
