name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest  # Используем macOS для совместимости с вашей средой

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew update
        brew install cmake sqlite gtest
        echo "CC=$(which clang)" >> $GITHUB_ENV
        echo "CXX=$(which clang++)" >> $GITHUB_ENV

    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Verify binary
      run: |
        ./bin/tourism_bureau --help || true
        file ./bin/tourism_bureau
